# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
