# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0002_auto_20161106_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
